// Code generated by github.com/dashotv/golem. DO NOT EDIT.
import axios from 'axios';

export const towerClient = axios.create({
  baseURL: '/api/tower',
});
towerClient.interceptors.request.use(config => {
  config.timeout = 30000;
  return config;
});

export interface Response {
  error: boolean;
  message: string;
}

export interface Setting {
  name: string;
  value: boolean;
}
