// Code generated by github.com/dashotv/golem. DO NOT EDIT.
import { Response, Setting, towerClient } from '.';

export interface ConfigSettingsRequest {
  id: string;
  settings: Setting;
}
export interface ConfigSettingsResponse extends Response {
  result: Setting;
}

export const ConfigSettings = async (params: ConfigSettingsRequest) => {
  const response = await towerClient.patch(`/config/${params.id}?`, params.settings);
  return response.data as ConfigSettingsResponse;
};
