// Code generated by github.com/dashotv/golem. DO NOT EDIT.
import { Directory, Response, towerClient } from '.';

export interface DirectoryIndexRequest {
  path: string;
  page: number;
  limit: number;
}
export interface DirectoryIndexResponse extends Response {
  result: Directory[];
  total: number;
}
export const DirectoryIndex = async (params: DirectoryIndexRequest) => {
  const response = await towerClient.get(
    `/directory/index?path=${params.path}&page=${params.page}&limit=${params.limit}`,
  );

  if (!response.data) {
    throw new Error('response empty?');
  }

  if (response.data.error) {
    if (response.data.message) {
      throw new Error(response.data.message);
    }
    throw new Error('unknown error');
  }

  return response.data as DirectoryIndexResponse;
};
