// Code generated by github.com/dashotv/golem. DO NOT EDIT.
import { Feed, Response, Setting, towerClient } from '.';

export interface FeedsIndexRequest {
  page: number;
  limit: number;
}
export interface FeedsIndexResponse extends Response {
  result: Feed[];
  total: number;
}
export interface FeedsCreateRequest {
  subject: Feed;
}
export interface FeedsCreateResponse extends Response {
  result: Feed;
}
export interface FeedsShowRequest {
  id: string;
}
export interface FeedsShowResponse extends Response {
  result: Feed;
}
export interface FeedsUpdateRequest {
  id: string;
  subject: Feed;
}
export interface FeedsUpdateResponse extends Response {
  result: Feed;
}
export interface FeedsSettingsRequest {
  id: string;
  setting: Setting;
}
export interface FeedsSettingsResponse extends Response {
  result: Feed;
}
export interface FeedsDeleteRequest {
  id: string;
}
export interface FeedsDeleteResponse extends Response {
  result: Feed;
}

export const FeedsIndex = async (params: FeedsIndexRequest) => {
  const response = await towerClient.get(`/feeds/?page=${params.page}&limit=${params.limit}`);
  return response.data as FeedsIndexResponse;
};
export const FeedsCreate = async (params: FeedsCreateRequest) => {
  const response = await towerClient.post(`/feeds/?`, params.subject);
  return response.data as FeedsCreateResponse;
};
export const FeedsShow = async (params: FeedsShowRequest) => {
  const response = await towerClient.get(`/feeds/${params.id}?`);
  return response.data as FeedsShowResponse;
};
export const FeedsUpdate = async (params: FeedsUpdateRequest) => {
  const response = await towerClient.put(`/feeds/${params.id}?`, params.subject);
  return response.data as FeedsUpdateResponse;
};
export const FeedsSettings = async (params: FeedsSettingsRequest) => {
  const response = await towerClient.patch(`/feeds/${params.id}?`, params.setting);
  return response.data as FeedsSettingsResponse;
};
export const FeedsDelete = async (params: FeedsDeleteRequest) => {
  const response = await towerClient.delete(`/feeds/${params.id}?`);
  return response.data as FeedsDeleteResponse;
};
