// Code generated by github.com/dashotv/golem. DO NOT EDIT.
import { Response, towerClient } from '.';

export const HooksPlex = async () => {
  const response = await towerClient.get(`/hooks/plex?`);
  return response.data as Response;
};
export const HooksNzbget = async () => {
  const response = await towerClient.get(`/hooks/nzbget?`);
  return response.data as Response;
};
