// Code generated by github.com/dashotv/golem. DO NOT EDIT.
import { Response, towerClient } from '.';

export const MessagesIndex = async () => {
  const response = await towerClient.get(`/messages/?`);
  return response.data as Response;
};
export const MessagesCreate = async () => {
  const response = await towerClient.post(`/messages/?`);
  return response.data as Response;
};
