// Code generated by github.com/dashotv/golem. DO NOT EDIT.
import { Path, Response, towerClient } from '.';

export interface PathsUpdateRequest {
  id: string;
  medium_id: string;
  path: Path;
}
export interface PathsUpdateResponse extends Response {
  result: Path;
}
export const PathsUpdate = async (params: PathsUpdateRequest) => {
  const response = await towerClient.post(`/paths/${params.id}?medium_id=${params.medium_id}`, params.path);

  if (!response.data) {
    throw new Error('response empty?');
  }

  if (response.data.error) {
    if (response.data.message) {
      throw new Error(response.data.message);
    }
    throw new Error('unknown error');
  }

  return response.data as PathsUpdateResponse;
};

export interface PathsDeleteRequest {
  id: string;
  medium_id: string;
}

export const PathsDelete = async (params: PathsDeleteRequest) => {
  const response = await towerClient.delete(`/paths/${params.id}?medium_id=${params.medium_id}`);

  if (!response.data) {
    throw new Error('response empty?');
  }

  if (response.data.error) {
    if (response.data.message) {
      throw new Error(response.data.message);
    }
    throw new Error('unknown error');
  }

  return response.data as Response;
};
