// Code generated by github.com/dashotv/golem. DO NOT EDIT.
import { Release, Response, Setting, towerClient } from '.';

export interface ReleasesIndexRequest {
  page: number;
  limit: number;
}
export interface ReleasesIndexResponse extends Response {
  result: Release[];
  total: number;
}
export interface ReleasesCreateRequest {
  subject: Release;
}
export interface ReleasesCreateResponse extends Response {
  result: Release;
}
export interface ReleasesShowRequest {
  id: string;
}
export interface ReleasesShowResponse extends Response {
  result: Release;
}
export interface ReleasesUpdateRequest {
  id: string;
  subject: Release;
}
export interface ReleasesUpdateResponse extends Response {
  result: Release;
}
export interface ReleasesSettingsRequest {
  id: string;
  setting: Setting;
}
export interface ReleasesSettingsResponse extends Response {
  result: Release;
}
export interface ReleasesDeleteRequest {
  id: string;
}
export interface ReleasesDeleteResponse extends Response {
  result: Release;
}
export interface ReleasesPopularRequest {
  interval: string;
}

export const ReleasesIndex = async (params: ReleasesIndexRequest) => {
  const response = await towerClient.get(`/releases/?page=${params.page}&limit=${params.limit}`);
  return response.data as ReleasesIndexResponse;
};
export const ReleasesCreate = async (params: ReleasesCreateRequest) => {
  const response = await towerClient.post(`/releases/?`, params.subject);
  return response.data as ReleasesCreateResponse;
};
export const ReleasesShow = async (params: ReleasesShowRequest) => {
  const response = await towerClient.get(`/releases/${params.id}?`);
  return response.data as ReleasesShowResponse;
};
export const ReleasesUpdate = async (params: ReleasesUpdateRequest) => {
  const response = await towerClient.put(`/releases/${params.id}?`, params.subject);
  return response.data as ReleasesUpdateResponse;
};
export const ReleasesSettings = async (params: ReleasesSettingsRequest) => {
  const response = await towerClient.patch(`/releases/${params.id}?`, params.setting);
  return response.data as ReleasesSettingsResponse;
};
export const ReleasesDelete = async (params: ReleasesDeleteRequest) => {
  const response = await towerClient.delete(`/releases/${params.id}?`);
  return response.data as ReleasesDeleteResponse;
};
export const ReleasesPopular = async (params: ReleasesPopularRequest) => {
  const response = await towerClient.get(`/releases/popular/${params.interval}?`);
  return response.data as Response;
};
