// Code generated by github.com/dashotv/golem. DO NOT EDIT.
import { Response, towerClient } from '.';

export const UpcomingIndex = async () => {
  const response = await towerClient.get(`/upcoming/?`);
  return response.data as Response;
};
