// Code generated by github.com/dashotv/golem. DO NOT EDIT.
import { Episode, Response, towerClient } from '.';

export interface UpcomingIndexResponse extends Response {
  result: Episode[];
  total: number;
}
export const UpcomingIndex = async () => {
  const response = await towerClient.get(`/upcoming/?`);

  if (!response.data) {
    throw new Error('response empty?');
  }

  if (response.data.error) {
    if (response.data.message) {
      throw new Error(response.data.message);
    }
    throw new Error('unknown error');
  }

  return response.data as UpcomingIndexResponse;
};
