// Code generated by github.com/dashotv/golem. DO NOT EDIT.
import { Response, User, towerClient } from '.';

export interface UsersIndexResponse extends Response {
  result: User[];
  total: number;
}

export const UsersIndex = async () => {
  const response = await towerClient.get(`/users/?`);
  return response.data as UsersIndexResponse;
};
