// Code generated by github.com/dashotv/golem. DO NOT EDIT.
import { Response, Wanted, towerClient } from '.';

export interface WantSeriesRequest {
  id: string;
}
export interface WantSeriesResponse extends Response {
  result: Wanted;
}
export const WantSeries = async (params: WantSeriesRequest) => {
  const response = await towerClient.get(`/want/series?id=${params.id}`);

  if (!response.data) {
    throw new Error('response empty?');
  }

  if (response.data.error) {
    if (response.data.message) {
      throw new Error(response.data.message);
    }
    throw new Error('unknown error');
  }

  return response.data as WantSeriesResponse;
};

export interface WantMovieRequest {
  id: string;
}
export interface WantMovieResponse extends Response {
  result: Wanted;
}
export const WantMovie = async (params: WantMovieRequest) => {
  const response = await towerClient.get(`/want/movie?id=${params.id}`);

  if (!response.data) {
    throw new Error('response empty?');
  }

  if (response.data.error) {
    if (response.data.message) {
      throw new Error(response.data.message);
    }
    throw new Error('unknown error');
  }

  return response.data as WantMovieResponse;
};
