// Code generated by github.com/dashotv/golem. DO NOT EDIT.
import { Response, Watch, towerClient } from '.';

export interface WatchesIndexRequest {
  medium_id: string;
  username: string;
}
export interface WatchesIndexResponse extends Response {
  result: Watch[];
  total: number;
}

export const WatchesIndex = async (params: WatchesIndexRequest) => {
  const response = await towerClient.get(`/watches/?medium_id=${params.medium_id}&username=${params.username}`);
  return response.data as WatchesIndexResponse;
};
