// Code generated by github.com/dashotv/golem. DO NOT EDIT.
import * as nzbget from './nzbget';
import * as qbt from './qbt';

export interface Combined {
  torrents?: qbt.Torrent[];
  nzbs?: nzbget.Group[];
  nzb_status?: nzbget.Status;
  metrics?: Metrics;
}
export interface Metrics {
  diskspace?: string;
  torrents?: TorrentRates;
  nzbs?: NzbRates;
}
export interface NzbRates {
  download_rate?: string;
}
export interface TorrentRates {
  download_rate?: string;
  upload_rate?: string;
}
