kind: pipeline
type: docker
name: default

steps:
  - name: publish
    image: plugins/docker
    environment:
      CLERK_KEY:
        from_secret: CLERK_KEY
    settings:
      registry: docker.dasho.tv
      username:
        from_secret: docker_dasho_username
      password:
        from_secret: docker_dasho_password
      repo: docker.dasho.tv/dashotv/ui
      tags:
        - latest
      build_args_from_env: [CLERK_KEY]
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        - 10.0.4.62
      port: 22
      username: deploy
      key:
        from_secret: ssh_key
      command_timeout: 2m
      script:
        - cd /srv/dashotv && docker compose pull -q ui && docker compose up -d --no-deps ui
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
    when:
      status: [success, failure]

trigger:
  branch:
    - main
  event:
    - push
    - custom
