kind: pipeline
type: docker
name: default

steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: dashotv/ui
      tags:
        - latest
      build_args_from_env: [REACT_APP_CLERK_PUBLISHABLE_KEY]
      environment:
        REACT_APP_CLERK_PUBLISHABLE_KEY:
          from_secret: REACT_APP_CLERK_PUBLISHABLE_KEY
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        - 10.0.4.61
      port: 22
      username: deploy
      key:
        from_secret: ssh_key
      command_timeout: 2m
      script:
        - sudo service dashotv restart
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook

trigger:
  branch:
    - main
  event:
    - push
