kind: pipeline
type: docker
name: default

steps:
  - name: publish
    image: plugins/docker
    environment:
      REACT_APP_CLERK_PUBLISHABLE_KEY:
        from_secret: CLERK_KEY
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: dashotv/ui
      tags:
        - latest
      build_args_from_env: [REACT_APP_CLERK_PUBLISHABLE_KEY]
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        - 10.0.4.61
      port: 22
      username: deploy
      key:
        from_secret: ssh_key
      command_timeout: 2m
      script:
        - cd /etc/dashotv && docker compose pull ui && docker compose restart ui
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
    when:
      status: [success, failure]

trigger:
  branch:
    - main
  event:
    - push
