nodeLinker: node-modules
npmScopes:
  dashotv:
    npmAlwaysAuth: true
    npmAuthToken: ${GITHUB_TOKEN:-}
    npmRegistryServer: 'https://npm.pkg.github.com'

npmRegistries:
  'https://npm.pkg.github.com':
    npmAuthToken: ${GITHUB_TOKEN:-}
    npmAlwaysAuth: true
