// Code generated by github.com/dashotv/golem. DO NOT EDIT.
import { PopularResponse, Response, runicClient } from '.';

export interface PopularIndexRequest {
  interval: string;
}
export interface PopularIndexResponse extends Response {
  result: PopularResponse;
  total: number;
}
export const PopularIndex = async (params: PopularIndexRequest) => {
  const response = await runicClient.get(`/popular/${params.interval}?`);

  if (!response.data) {
    throw new Error('response empty?');
  }

  if (response.data.error) {
    if (response.data.message) {
      throw new Error(response.data.message);
    }
    throw new Error('unknown error');
  }

  return response.data as PopularIndexResponse;
};
