// Code generated by github.com/dashotv/golem. DO NOT EDIT.

export interface Medium {
  id?: string;
  created_at?: string;
  updated_at?: string;

  type?: string;
  kind?: string;
  source?: string;
  source_id?: string;
  imdb_id?: string;
  title?: string;
  description?: string;
  display?: string;
  directory?: string;
  search?: string;
  active?: boolean;
  downloaded?: boolean;
  completed?: boolean;
  skipped?: boolean;
  watched?: boolean;
  broken?: boolean;
  favorite?: boolean;
  unwatched?: number;
  release_date?: string;
  paths?: Path[];
  cover?: string;
  background?: string;
  status?: string;
  series_id?: string;
  season_number?: number;
  episode_number?: number;
  absolute_number?: number;
}
export interface Path {
  id?: string;
  type?: string;
  tag?: string;
  remote?: string;
  local?: string;
  extension?: string;
  size?: number;
  resolution?: number;
  bitrate?: number;
  checksum?: string;
  updated_at?: string;
  old?: boolean;
  rename?: boolean;
}
export interface SearchAllResponse {
  media?: SearchResponse;
  tmdb?: SearchResponse;
  tvdb?: SearchResponse;
}
export interface SearchResponse {
  results?: SearchResult[];
  error?: string;
}
export interface SearchResult {
  id?: string;
  title?: string;
  description?: string;
  type?: string;
  kind?: string;
  date?: string;
  source?: string;
  image?: string;
  completed?: boolean;
}
