// Code generated by github.com/dashotv/golem. DO NOT EDIT.

export interface SearchAllResponse {
  media?: SearchResponse;
  tmdb?: SearchResponse;
  tvdb?: SearchResponse;
}

export interface SearchResponse {
  results?: SearchResult[];
  error?: string;
}

export interface SearchResult {
  id?: string;
  title?: string;
  description?: string;
  type?: string;
  kind?: string;
  date?: string;
  source?: string;
  image?: string;
}
