// Code generated by github.com/dashotv/golem. DO NOT EDIT.
import { Response, scryClient } from '.';
import * as nzbgeek from './nzbgeek';

export interface NzbsMovieResponse extends Response {
  result: nzbgeek.SearchResult[];
}
export const NzbsMovie = async () => {
  const response = await scryClient.get(`/nzbs/movie?`);

  if (!response.data) {
    throw new Error('response empty?');
  }

  if (response.data.error) {
    if (response.data.message) {
      throw new Error(response.data.message);
    }
    throw new Error('unknown error');
  }

  return response.data as NzbsMovieResponse;
};

export interface NzbsTvResponse extends Response {
  result: nzbgeek.SearchResult[];
}
export const NzbsTv = async () => {
  const response = await scryClient.get(`/nzbs/tv?`);

  if (!response.data) {
    throw new Error('response empty?');
  }

  if (response.data.error) {
    if (response.data.message) {
      throw new Error(response.data.message);
    }
    throw new Error('unknown error');
  }

  return response.data as NzbsTvResponse;
};
