// Code generated by github.com/dashotv/golem. DO NOT EDIT.
import { Response, SearchAllResponse, scryClient } from '.';

export interface SearchIndexRequest {
  start: number;
  limit: number;
  type: string;
  q: string;
  name: string;
}
export interface SearchIndexResponse extends Response {
  result: SearchAllResponse;
  total: number;
}
export const SearchIndex = async (params: SearchIndexRequest) => {
  const response = await scryClient.get(
    `/search/?start=${params.start}&limit=${params.limit}&type=${params.type}&q=${params.q}&name=${params.name}`,
  );

  if (!response.data) {
    throw new Error('response empty?');
  }

  if (response.data.error) {
    if (response.data.message) {
      throw new Error(response.data.message);
    }
    throw new Error('unknown error');
  }

  return response.data as SearchIndexResponse;
};
